#!/bin/bash

# ─────────────────────────────────────────
#  ACCOUNTABILI-BUDDY — Installer
# ─────────────────────────────────────────

NC=$'\e[0m'
PLUM=$'\e[38;5;13m'
SKY=$'\e[38;5;45m'
LIME=$'\e[38;5;106m'
TEAL=$'\e[38;5;43m'
YELLOW=$'\e[38;5;220m'
GREY=$'\e[38;5;60m'
PINK=$'\e[38;5;219m'
ORANGE=$'\e[38;5;214m'
LAVENDER=$'\e[38;5;141m'

# ── INTRO ──

echo ""
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo -e "${SKY}  ACCOUNTABILI-BUDDY INTRO${NC}"
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo ""
echo -e "૮(„• ⌔ •„)ა ${PLUM}Hi!${NC}"
    sleep 0.5
echo -e "${PLUM}🐧I'm Abuddy — a terminal-based focus timer${NC}"
echo -e "${PLUM}with built-in self care breaks, session logging,${NC}"
echo -e "${PLUM}and a wins tracker so you remember what you've${NC}"
echo -e "${PLUM}already pulled off.${NC}"
echo ""
echo -e "${PLUM}The Pomodoro technique breaks work into focused${NC}"
echo -e "${PLUM}sessions with short breaks between them. I do${NC}"
echo -e "${PLUM}that — and then a little more.${NC}"
echo ""
echo -e "${GREY}Here's what this installer is going to do:${NC}"
echo -e "${GREY}  1. Choose where to put your files${NC}"
echo -e "${GREY}  2. Set up your list files with starter content${NC}"
echo -e "${GREY}  3. Optionally add an 'abuddy' shortcut command${NC}"
echo -e "${GREY}  4. Run a quick demo so you know what to expect${NC}"
echo ""
read -p "$(echo -e "${LIME}Press Enter to get started (Step 1 of 4)...${NC}")" dummy

# ── STEP 1 — DIRECTORY ──

echo ""
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo -e "${SKY}  STEP 1 OF 4 — WHERE TO PUT YOUR FILES${NC}"
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo ""
echo -e "૮(„• ⌔ •„)ა💾"
echo -e "${PLUM}I'll create a folder to store your list files,${NC}"
echo -e "${PLUM}config, and session logs.${NC}"
echo ""
echo -e "${PLUM}The default is ${TEAL}~/.abuddy${PLUM} — a hidden directory.${NC}"
echo -e "${PLUM}On Linux, folders starting with a dot are hidden${NC}"
echo -e "${PLUM}from normal file listings. You won't see it with${NC}"
echo -e "${PLUM}just ${TEAL}ls${PLUM} — use ${TEAL}ls -a${PLUM} to show hidden items.${NC}"
echo -e "${PLUM}This is normal and intentional. Your files are${NC}"
echo -e "${PLUM}still there — they're just tucked away.${NC}"
echo ""
read -p "$(echo -e "${LIME}Press Enter to use ~/.abuddy, or type a custom path: ${NC}")" INPUT_DIR

if [ -z "$INPUT_DIR" ]; then
    ABUDDY_DIR="$HOME/.abuddy"
else
    # Expand ~ manually in case user types it
    ABUDDY_DIR="${INPUT_DIR/#\~/$HOME}"
fi

while true; do
    echo ""
    echo -e "${TEAL}Install directory: $ABUDDY_DIR${NC}"
    read -p "$(echo -e "${LIME}Confirm? (Enter to continue, or type 'no' to change): ${NC}")" CONFIRM_DIR

    if [ "$CONFIRM_DIR" != "no" ]; then
        break
    fi

    read -p "$(echo -e "${LIME}Enter your preferred path: ${NC}")" INPUT_DIR
    ABUDDY_DIR="${INPUT_DIR/#\~/$HOME}"
done

mkdir -p "$ABUDDY_DIR"
echo ""
sleep 0.5
echo -e "${LIME}Created: $ABUDDY_DIR${NC}"
echo ""
read -p "$(echo -e "${LIME}Press Enter to continue (Step 2 of 4)...${NC}")" dummy

# ── STEP 2 — FILES ──

echo ""
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo -e "${SKY}  STEP 2 OF 4 — SETTING UP YOUR FILES${NC}"
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo ""
echo -e "૮(„• ⌔ •„)ა📝"
echo -e "${PLUM}I'm going to copy the script, write your config,${NC}"
echo -e "${PLUM}and create your list files with some starter${NC}"
echo -e "${PLUM}content. You can edit any of these files later${NC}"
echo -e "${PLUM}to make them your own.${NC}"
echo ""
read -p "$(echo -e "${LIME}Press Enter to continue...${NC}")" dummy

# Copy abuddy.sh
SCRIPT_SOURCE="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" &>/dev/null && pwd)/abuddy.sh"

if [ ! -f "$SCRIPT_SOURCE" ]; then
    echo ""
    echo -e "${PINK}Could not find abuddy.sh in the same directory as install.sh.${NC}"
    echo -e "${PINK}Make sure both files are in the same folder before running the installer.${NC}"
    exit 1
fi

cp "$SCRIPT_SOURCE" "$ABUDDY_DIR/abuddy.sh"
chmod 700 "$ABUDDY_DIR/abuddy.sh"
sleep 0.1
echo -e "${LIME}Copied:  $ABUDDY_DIR/abuddy.sh${NC}"

# Write abuddy.cfg
cat > "$ABUDDY_DIR/abuddy.cfg" << EOF
# abuddy.cfg
# Generated by install.sh — edit this file to customize your setup.
# abuddy.sh sources this file on every run.

# ── INSTALL PATH ──
ABUDDY_DIR="$ABUDDY_DIR"

# ── TIMER DEFAULTS ──
# Used when you press Enter without typing a value at the setup prompts.
# All values are in minutes.
DEFAULT_WORK=25
DEFAULT_BREAK=5
DEFAULT_SESSIONS=4

# ── FILE PATHS ──
# Built from ABUDDY_DIR — no need to edit these directly.
EXERCISES="\$ABUDDY_DIR/exercises.txt"
NUDGES="\$ABUDDY_DIR/nudges.txt"
GOALS="\$ABUDDY_DIR/goals.txt"
REFLECTIONS="\$ABUDDY_DIR/reflections.txt"
WINS_FILE="\$ABUDDY_DIR/wins.txt"
LOG="\$ABUDDY_DIR/abuddy.log.md"
EOF

chmod 600 "$ABUDDY_DIR/abuddy.cfg"
sleep 0.5
echo -e "${LIME}Created: $ABUDDY_DIR/abuddy.cfg${NC}"

# Create list files with starter content

cat > "$ABUDDY_DIR/exercises.txt" << 'EOF'
Move away from your work area for a minute
Roll your shoulders back ten times
Stretch your neck slowly side to side
Do a low impact short cardio exercise that makes sense for you
Refill your water and take a few sips before sitting back down
Go outside or to a window for sixty seconds
EOF

cat > "$ABUDDY_DIR/nudges.txt" << 'EOF'
How's your posture right now?
Have you had water recently?
Take three slow breaths before the next session
Blink a few times and look at something across the room
Check in — how are you actually feeling?
You're doing the thing. That counts.
EOF

cat > "$ABUDDY_DIR/goals.txt" << 'EOF'
Finish one topic you've been putting off
Review your notes from this week
Work through one practice problem set
Read one chapter or module
Tidy up your notes from last session
EOF

cat > "$ABUDDY_DIR/reflections.txt" << 'EOF'
What went well this session?
What would you do differently next time?
What's one thing you actually learned today?
What's still on your mind that you haven't dealt with yet?
What are you proud of from today?
EOF

cat > "$ABUDDY_DIR/wins.txt" << 'EOF'
You installed abuddy. That's a win.
You showed up. Seriously, that matters.
You're building something. Keep going.
EOF

# Set data file permissions — 600: owner read/write only
chmod 600 "$ABUDDY_DIR/exercises.txt"
chmod 600 "$ABUDDY_DIR/nudges.txt"
chmod 600 "$ABUDDY_DIR/goals.txt"
chmod 600 "$ABUDDY_DIR/reflections.txt"
chmod 600 "$ABUDDY_DIR/wins.txt"

sleep 0.2
echo -e "${LIME}Created: $ABUDDY_DIR/exercises.txt${NC}"
sleep 0.2
echo -e "${LIME}Created: $ABUDDY_DIR/nudges.txt${NC}"
sleep 0.2
echo -e "${LIME}Created: $ABUDDY_DIR/goals.txt${NC}"
sleep 0.2
echo -e "${LIME}Created: $ABUDDY_DIR/reflections.txt${NC}"
sleep 0.2
echo -e "${LIME}Created: $ABUDDY_DIR/wins.txt${NC}"
sleep 0.2
echo -e "${LIME}All starter files created.${NC}"
sleep 0.2
echo ""
echo -e "${PLUM}All files are yours to edit. Add, remove, or${NC}"
echo -e "${PLUM}rewrite any entries to make abuddy your own.${NC}"
echo ""
read -p "$(echo -e "${LIME}Press Enter to continue (Step 3 of 4)...${NC}")" dummy
# ── STEP 3 — ALIAS ──

echo ""
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo -e "${SKY}  STEP 3 OF 4 — SHORTCUT COMMAND${NC}"
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo ""
echo -e "૮(„• ⌔ •„)ა⌨"
echo -e "${PLUM}An alias is a shortcut — instead of typing the${NC}"
echo -e "${PLUM}full path to run abuddy, you could just type${NC}"
echo -e "${TEAL}abuddy${PLUM} from anywhere.${NC}"
echo ""
echo -e "${PLUM}This adds one line to your ${TEAL}~/.bash_aliases${PLUM} file,${NC}"
echo -e "${PLUM}which your shell loads automatically on login.${NC}"
echo -e "${PLUM}You can remove it any time by editing that file.${NC}"
echo ""
read -p "$(echo -e "${LIME}Add 'abuddy' as a shortcut command? (y/n): ${NC}")" ADD_ALIAS

if [ "$ADD_ALIAS" = "y" ] || [ "$ADD_ALIAS" = "Y" ]; then
    ALIAS_LINE="alias abuddy='bash $ABUDDY_DIR/abuddy.sh'"

    # Create ~/.bash_aliases if it doesn't exist
    if [ ! -f "$HOME/.bash_aliases" ]; then
        touch "$HOME/.bash_aliases"
        sleep 0.2
        echo -e "${LIME}Created ~/.bash_aliases${NC}"
    fi

    # Check if alias already exists
    if grep -q "alias abuddy=" "$HOME/.bash_aliases"; then
        echo ""
        sleep 0.2
        echo -e "${YELLOW}An 'abuddy' alias already exists in ~/.bash_aliases.${NC}"
        echo -e "${YELLOW}Skipping to avoid duplicates. Edit the file manually if you need to update it.${NC}"
    else
        echo "" >> "$HOME/.bash_aliases"
        echo "# accountabili-buddy" >> "$HOME/.bash_aliases"
        echo "$ALIAS_LINE" >> "$HOME/.bash_aliases"
        sleep 0.2
        echo ""
        echo -e "${LIME}Alias added to ~/.bash_aliases${NC}"
        echo ""
        echo -e "${PLUM}To use it in this terminal session right now, run:${NC}"
        echo -e "${TEAL}  source ~/.bash_aliases${NC}"
        echo -e "${PLUM}Or just open a new terminal — it will load automatically.${NC}"
    fi
else
    echo ""
    echo -e "${PLUM}No problem. You can run abuddy any time with:${NC}"
    echo -e "${TEAL}  bash $ABUDDY_DIR/abuddy.sh${NC}"
fi
echo ""
read -p "$(echo -e "${LIME}Press Enter to continue (Step 4 of 4)...${NC}")" dummy
# ── STEP 4 — DEMO ──

echo ""
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo -e "${SKY}  STEP 4 OF 4 — QUICK DEMO${NC}"
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo ""
echo -e "૮(„• ⌔ •„)ა⧗"
echo -e "${PLUM}Let me show you what a session looks like.${NC}"
echo -e "${PLUM}This isn't a real timer — just a walkthrough${NC}"
echo -e "${PLUM}so you know what to expect and how to interact.${NC}"
echo ""
read -p "$(echo -e "${LIME}Run the demo? (y/n): ${NC}")" RUN_DEMO

if [ "$RUN_DEMO" = "y" ] || [ "$RUN_DEMO" = "Y" ]; then

    echo ""
    echo -e "${LAVENDER}── THE SETUP BLOCK ────────────────────────────${NC}"
    echo ""
    echo -e "૮(„• ⌔ •„)ა☀"
    echo -e "${PLUM}I start out by helping you build your intention${NC}"
    echo -e "${PLUM}for your study session as well as the length.${NC}"
    echo -e "${PLUM}It's usually recommended to not do more than${NC}"
    echo -e "${PLUM}four blocks in a session and to take a big break${NC}"
    echo -e "${PLUM}afterwards.${NC}"
    echo -e ""
    echo -e "${ORANGE}What's your goal for this session? (demo mode): ${NC}"
    echo -e "${PLUM}>*To learn about abuddy and what makes them unique.* Enter${NC}"
    echo -e ""
    echo -e "${PINK}Any specific reminders for this session? (demo mode): ${NC}"
    echo -e "${PLUM}>*To check the laundry. Oh, or to send that text message!* Enter${NC}"
    echo -e ""
    read -p "$(echo -e "${LIME}Press Enter to continue the demo...${NC}")" dummy

    echo ""
    echo -e "${LAVENDER}── THE WORK BLOCK ───────────────────────────${NC}"
    echo ""
    echo -e "${PLUM}When a session starts you'll see something like this:${NC}"
    echo ""
    echo -e "${SKY}─────────────────────────────────────────${NC}"
    echo -e "${SKY}  SESSION 1 of 4${NC}"
    echo -e "${SKY}─────────────────────────────────────────${NC}"
    echo ""
    echo -e "${TEAL}  Goal: To learn about abuddy and what makes them unique${NC}"
    echo ""
    echo -e "Started: ${TEAL} $(date +"%I:%M %p")${NC}"
    echo -e "Expected break:${PINK}  $(date -d "+25 minutes" +"%I:%M %p")${NC}"
    echo -e "${GREY}Press Enter at any time to skip to break.${NC}"
    echo ""
    echo -e "${PLUM}The timer runs silently. Work until it ends,${NC}"
    echo -e "${PLUM}or press Enter early when you reach a good stopping point.${NC}"
    echo ""
    read -p "$(echo -e "${LIME}Press Enter to continue the demo...${NC}")" dummy

    echo ""
    echo -e "${LAVENDER}── THE BREAK BLOCK ──────────────────────────${NC}"
    echo ""
    echo -e "૮(„• ⌔ •„)ა☕"
    echo -e "${PLUM}After each work block, you'll be prompted to start${NC}"
    echo -e "${PLUM}the break, just in case you need to wrap up some work first.${NC}"
    echo ""
    echo -e "${PLUM}This is where your reminder comes into play:${NC}"
    echo ""
    echo -e "${SKY}─────────────────────────────────────────${NC}"
    echo -e "${SKY}  BREAK — 5 minutes${NC}"
    echo -e "${SKY}─────────────────────────────────────────${NC}"
    echo ""
    echo -e "${PINK}★ Don't forget: To check the laundry. Oh, or to send that text message!${NC}"
    echo -e "${PLUM}If you left it empty though, this won't show up${NC}"
    echo -e ""
    echo -e "${PLUM}And then I'll give you a suggestion for your break:${NC}"
    echo -e ""
    echo -e "${TEAL}  Stand up and walk around for a minute${NC}"
    echo -e "${ORANGE} X minutes remaining...${NC}"
    echo ""
    echo -e "${PLUM}Suggestions rotate every minute through the break.${NC}"
    echo -e "${PLUM}You can press enter to skip, or let it run.${NC}"
    echo -e "${PLUM}I suggest letting it run, you earned the break!${NC}"
    echo ""
    echo -e "૮(„• ⌔ •„)ა⧖"
    echo -e "${PLUM}End of break will let you change your goal and reminder${NC}"
    echo -e "${PLUM}for the next work block and break. The session will only${NC}"
    echo -e "${PLUM}progress when you hit enter - just in case you were${NC}"
    echo -e "${PLUM}still getting that glass of water.${NC}"
    echo ""
    read -p "$(echo -e "${LIME}Press Enter to continue the demo...${NC}")" dummy

    echo ""
    echo -e "${LAVENDER}── THE END BLOCK ────────────────────────────${NC}"
    echo ""
    echo -e "૮(„• ⌔ •„)ა✨"
    echo -e "${PLUM}After all your sessions, I'll ask a reflection${NC}"
    echo -e "${PLUM}question and give you space to log a win.${NC}"
    echo -e "${PLUM}Both get saved to your session log.${NC}"
    echo ""
    echo -e "${SKY}─────────────────────────────────────────${NC}"
    echo -e "${SKY}  SESSION COMPLETE${NC}"
    echo -e "${SKY}─────────────────────────────────────────${NC}"
    echo ""
    echo -e "${TEAL}  4 blocks done. Nice work.${NC}"
    echo ""
    echo -e "${ORANGE}Reflection: What went well this session? (demo mode):${NC}"
    echo -e "${PLUM}>*I got through the abuddy tutorial*${NC}"
    echo ""
    echo -e "${YELLOW}One win from this session — keep it to one sentence. (demo mode):${NC}"
    echo -e "${PLUM}>*I'm trying something out*${NC}"
    echo ""
    read -p "$(echo -e "${LIME}Press Enter to continue the demo...${NC}")" dummy

    echo ""
    echo -e "${LAVENDER}── The Log Block ────────────────────────────${NC}"
    echo ""
    echo -e "${PLUM}The log writes your start time and end time into${NC}"
    echo -e "${PLUM}a block along with all your goals, your reflection,${NC}"
    echo -e "${PLUM}and your win for you to reference later as needed.${NC}"
    echo -e "${PLUM}It's a good reminder of what you did accomplish and${NC}"
    echo -e "${PLUM}a resource for preparing for another session${NC}"
    echo ""
    echo -e "૮(„• ⌔ •„)ა♡"
    echo -e "${PLUM}Wins additionally go into another file to remind you${NC}"
    echo -e "${PLUM}at the start of each session what you know you've done well.${NC}"
    echo -e "${PLUM}Proof that you believe in you too!${NC}"
    echo ""
    read -p "$(echo -e "${LIME}Press Enter to continue the demo...${NC}")" dummy

    # Bell test
    echo ""
    echo -e "${LAVENDER}── BELL TEST ────────────────────────────────${NC}"
    echo ""
    echo -e "૮(„• ⌔ •„)ა♪ ♫"
    echo -e "${PLUM}I ring a bell at transitions — work to break,${NC}"
    echo -e "${PLUM}break to work. To test, be sure your sound is on.${NC}"
    echo ""
    read -p "$(echo -e "${LIME}Press Enter to ring the bell...${NC}")" dummy
    echo -e "\a"
    echo ""
    echo -e "${PLUM}Did you hear something?${NC}"
    echo ""
    read -p "$(echo -e "${LIME}(y/n): ${NC}")" HEARD_BELL

    if [ "$HEARD_BELL" = "n" ] || [ "$HEARD_BELL" = "N" ]; then
        echo ""
        echo -e "${YELLOW}No sound — that's a common terminal setting.${NC}"
        echo -e "${YELLOW}Check the README for fixes. The short version:${NC}"
        echo ""
        echo -e "${GREY}  VS Code:   Settings → Features → Accessibility Signals → ${NC}"
        echo -e "${GREY}        Signals: Terminal Bell → sound: on${NC}"
        echo -e "${GREY}  Other terminals: check your terminal's sound or bell settings${NC}"
        echo -e "${GREY}  PowerShell SSH:  bell usually works without any changes${NC}"
        echo ""
        echo -e "${PLUM}The timer works fine without the bell —${NC}"
        echo -e "${PLUM}you just won't get an audio nudge at transitions.${NC}"
    else
        echo ""
        echo -e "${LIME}You're all set.${NC}"
    fi

fi
read -p "$(echo -e "${LIME}Press Enter to recap...${NC}")" dummy
# ── SUMMARY ──

echo ""
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo -e "${SKY}  YOU'RE READY${NC}"
echo -e "${SKY}─────────────────────────────────────────${NC}"
echo ""
echo -e "૮(„• ⌔ •„)ა[✓]"
echo -e "${PLUM}Here's where everything landed:${NC}"
echo ""
echo -e "${TEAL}  Script:  $ABUDDY_DIR/abuddy.sh${NC}"
echo -e "${TEAL}  Config:  $ABUDDY_DIR/abuddy.cfg${NC}"
echo -e "${TEAL}  Lists:   $ABUDDY_DIR/*.txt${NC}"
echo -e "${TEAL}  Log:     $ABUDDY_DIR/abuddy.log.md${NC}"
echo ""
echo -e "${PLUM}To run abuddy:${NC}"
if [ "$ADD_ALIAS" = "y" ] || [ "$ADD_ALIAS" = "Y" ]; then
    echo -e "${TEAL}  abuddy${NC}"
    echo -e "${GREY}  (after sourcing ~/.bash_aliases or opening a new terminal)${NC}"
else
    echo -e "${TEAL}  bash $ABUDDY_DIR/abuddy.sh${NC}"
fi
echo ""
echo -e "${PLUM}To make it yours — open any .txt file in your${NC}"
echo -e "${PLUM}install directory and edit the entries. One item${NC}"
echo -e "${PLUM}per line. That's it.${NC}"
echo ""
echo -e "${PLUM}Good luck out there.${NC}"
echo ""
echo -e "✦ ૮(„^ ⌔ ^„)ა✦"